# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "03:00"
      timezone: "America/New_York"
    commit-message:
      prefix: '#patch'
  - package-ecosystem: "bundler" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "03:00"
      timezone: "America/New_York"
    commit-message:
      prefix: '#patch'
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "03:00"
      timezone: "America/New_York"
    commit-message:
      prefix: '#patch'
    groups:
      gradle-plugin-dependencies:
        patterns:
          - "com.android.application"
          - "com.android.library"
      kotlin-dependencies:
        patterns:
          - "org.jetbrains.kotlin.android"
          - "org.jetbrains.kotlin.plugin.compose"
          - "com.google.devtools.ksp"
      hilt-dependencies:
        patterns:
          - "*hilt*"