name: Version Checks

on:
  pull_request:
    branches:
      - main

jobs:
  get-target-project-version:
    runs-on: ubuntu-latest
    outputs:
      project-version: ${{ steps.get-version.outputs.version }}
    steps:
      - id: checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.base_ref }}
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
      - id: get-version
        run: echo "version=$(./gradlew --no-daemon -q printVersionName)" >> "$GITHUB_OUTPUT"
  get-source-project-version:
    runs-on: ubuntu-latest
    outputs:
      project-version: ${{ steps.get-version.outputs.version }}
    steps:
      - id: checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
      - id: get-version
        run: echo "version=$(./gradlew --no-daemon -q printVersionName)" >> "$GITHUB_OUTPUT"
  ensure-new-version:
    runs-on: ubuntu-latest
    needs: [get-target-project-version, get-source-project-version]
    steps:
      - name: Compare
        run: |
          TARGET="${{ needs.get-target-project-version.steps.outputs.project-version }}"
          SOURCE="${{ needs.get-source-project-version.steps.outputs.project-version }}"
          if [ "$TARGET" == "$SOURCE" ]; then
            echo "Failure: Project versions should not remain the same on merging to main"
            exit 1
          else
            echo "Success: Project version differs from main"
            exit 0
          fi