name: Version Update

on:
  pull_request:
    branches:
      - main

jobs:
  determine-new-version:
    uses: seamuslowry/workflows/.github/workflows/tag.yml@main
    with:
      dry-run: true
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
  ensure-new-version:
    runs-on: ubuntu-latest
    needs: determine-new-version
    steps:
      # set up
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      # main branch versions
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.base_ref }}
      - run: |
          echo "version-name=$(./gradlew --no-daemon -q printVersionName)" >> "$GITHUB_OUTPUT"
        id: main-branch-version-name
      - run: |
          echo "version-code=$(./gradlew --no-daemon -q printVersionCode)" >> "$GITHUB_OUTPUT"
        id: main-branch-version-code

      # checkout to PR branch
      - uses: actions/checkout@v4
      # update versions
      - name: Update versions
        run: |
          echo "$(git branch --show-current)"
          sed -n "s/versionName \"${{ steps.main-branch-version-name.outputs.version-name }}\"/versionName \"${{ needs.determine-new-version.outputs.tag }}\"/" app/build.gradle
          sed -n "s/versionCode ${{ steps.main-branch-version-code.outputs.version-code }}/versionCode $(( ${{ steps.main-branch-version-code.outputs.version-code }} + 1 ))/" app/build.gradle
          echo "$(git --no-pager diff)"