name: Tag

on:
  pull_request:
    branches:
      - main

jobs:
  get-source-project-version:
    runs-on: ubuntu-latest
    outputs:
      project-version: ${{ steps.get-version.outputs.version }}
    steps:
      - id: checkout
        uses: actions/checkout@v3
        with:
          - ref: ${{ github.base_ref }}
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
      - id: get-version
        run: echo "version=$(./gradlew --no-daemon -q printVersionName)" >> "$GITHUB_OUTPUT"
  get-target-project-version:
    runs-on: ubuntu-latest
    outputs:
      project-version: ${{ steps.get-version.outputs.version }}
    steps:
      - id: checkout
        uses: actions/checkout@v3
        with:
          - ref: ${{ github.head_ref }}
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
      - id: get-version
        run: echo "version=$(./gradlew --no-daemon -q printVersionName)" >> "$GITHUB_OUTPUT"